// This file is auto-generated by `supabase gen types typescript`.
// Placeholder until generated from actual Supabase instance.

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          domain: string | null;
          owner_user_id: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          plan: "free" | "starter" | "professional" | "enterprise";
          monthly_email_limit: number;
          emails_sent_this_month: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          domain?: string | null;
          owner_user_id: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          plan?: "free" | "starter" | "professional" | "enterprise";
          monthly_email_limit?: number;
          emails_sent_this_month?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["organizations"]["Insert"]>;
      };
      prospects: {
        Row: {
          id: string;
          org_id: string;
          email: string;
          first_name: string;
          last_name: string;
          title: string | null;
          company_name: string | null;
          company_domain: string | null;
          company_size: string | null;
          industry: string | null;
          linkedin_url: string | null;
          phone: string | null;
          location: string | null;
          status: string;
          enrichment_data: Record<string, unknown> | null;
          recent_posts: string[] | null;
          mutual_connections: string[] | null;
          embedding: number[] | null;
          tags: string[];
          last_contacted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          email: string;
          first_name: string;
          last_name: string;
          title?: string | null;
          company_name?: string | null;
          company_domain?: string | null;
          company_size?: string | null;
          industry?: string | null;
          linkedin_url?: string | null;
          phone?: string | null;
          location?: string | null;
          status?: string;
          enrichment_data?: Record<string, unknown> | null;
          recent_posts?: string[] | null;
          mutual_connections?: string[] | null;
          tags?: string[];
          last_contacted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["prospects"]["Insert"]>;
      };
      campaigns: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          description: string | null;
          status: string;
          icp_profile_id: string | null;
          writing_sample_id: string | null;
          daily_send_limit: number;
          timezone: string;
          send_window_start: string;
          send_window_end: string;
          send_days: number[];
          total_prospects: number;
          total_sent: number;
          total_opened: number;
          total_replied: number;
          total_meetings: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          description?: string | null;
          status?: string;
          icp_profile_id?: string | null;
          writing_sample_id?: string | null;
          daily_send_limit?: number;
          timezone?: string;
          send_window_start?: string;
          send_window_end?: string;
          send_days?: number[];
        };
        Update: Partial<Database["public"]["Tables"]["campaigns"]["Insert"]>;
      };
      sequences: {
        Row: {
          id: string;
          org_id: string;
          campaign_id: string;
          name: string;
          description: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          campaign_id: string;
          name: string;
          description?: string | null;
          is_active?: boolean;
        };
        Update: Partial<Database["public"]["Tables"]["sequences"]["Insert"]>;
      };
      sequence_steps: {
        Row: {
          id: string;
          sequence_id: string;
          step_number: number;
          step_type: string;
          delay_days: number;
          subject_template: string | null;
          body_template: string | null;
          ai_generated: boolean;
          ab_test_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          sequence_id: string;
          step_number: number;
          step_type?: string;
          delay_days?: number;
          subject_template?: string | null;
          body_template?: string | null;
          ai_generated?: boolean;
          ab_test_id?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["sequence_steps"]["Insert"]>;
      };
      emails_sent: {
        Row: {
          id: string;
          org_id: string;
          prospect_id: string;
          campaign_id: string;
          sequence_id: string;
          step_id: string;
          from_email: string;
          to_email: string;
          subject: string;
          body_html: string;
          body_text: string;
          status: string;
          sendgrid_message_id: string | null;
          opened_at: string | null;
          clicked_at: string | null;
          bounced_at: string | null;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          prospect_id: string;
          campaign_id: string;
          sequence_id: string;
          step_id: string;
          from_email: string;
          to_email: string;
          subject: string;
          body_html: string;
          body_text: string;
          status?: string;
          sendgrid_message_id?: string | null;
          sent_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["emails_sent"]["Insert"]>;
      };
      email_replies: {
        Row: {
          id: string;
          org_id: string;
          email_sent_id: string;
          prospect_id: string;
          campaign_id: string;
          from_email: string;
          subject: string | null;
          body_text: string;
          body_html: string | null;
          classification: string | null;
          sentiment_score: number | null;
          ai_suggested_response: string | null;
          is_handled: boolean;
          handled_at: string | null;
          nylas_message_id: string | null;
          received_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          email_sent_id: string;
          prospect_id: string;
          campaign_id: string;
          from_email: string;
          subject?: string | null;
          body_text: string;
          body_html?: string | null;
          classification?: string | null;
          sentiment_score?: number | null;
          ai_suggested_response?: string | null;
          is_handled?: boolean;
          nylas_message_id?: string | null;
          received_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["email_replies"]["Insert"]>;
      };
      meetings_booked: {
        Row: {
          id: string;
          org_id: string;
          prospect_id: string;
          campaign_id: string;
          title: string;
          description: string | null;
          start_time: string;
          end_time: string;
          meeting_link: string | null;
          calendar_event_id: string | null;
          status: string;
          outcome_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          prospect_id: string;
          campaign_id: string;
          title: string;
          description?: string | null;
          start_time: string;
          end_time: string;
          meeting_link?: string | null;
          calendar_event_id?: string | null;
          status?: string;
        };
        Update: Partial<Database["public"]["Tables"]["meetings_booked"]["Insert"]>;
      };
      icp_profiles: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          description: string | null;
          target_titles: string[];
          target_industries: string[];
          target_company_sizes: string[];
          target_locations: string[];
          pain_points: string[];
          value_propositions: string[];
          keywords: string[];
          exclude_domains: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          description?: string | null;
          target_titles?: string[];
          target_industries?: string[];
          target_company_sizes?: string[];
          target_locations?: string[];
          pain_points?: string[];
          value_propositions?: string[];
          keywords?: string[];
          exclude_domains?: string[];
        };
        Update: Partial<Database["public"]["Tables"]["icp_profiles"]["Insert"]>;
      };
      writing_samples: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          tone: string;
          example_emails: string[];
          guidelines: string | null;
          signature: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          tone?: string;
          example_emails?: string[];
          guidelines?: string | null;
          signature?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["writing_samples"]["Insert"]>;
      };
      ab_tests: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          step_id: string;
          variant_a_subject: string;
          variant_a_body: string;
          variant_b_subject: string;
          variant_b_body: string;
          variant_a_sent: number;
          variant_b_sent: number;
          variant_a_opened: number;
          variant_b_opened: number;
          variant_a_replied: number;
          variant_b_replied: number;
          winner: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          step_id: string;
          variant_a_subject: string;
          variant_a_body: string;
          variant_b_subject: string;
          variant_b_body: string;
        };
        Update: Partial<Database["public"]["Tables"]["ab_tests"]["Insert"]>;
      };
      integrations: {
        Row: {
          id: string;
          org_id: string;
          type: string;
          is_connected: boolean;
          config: Record<string, unknown>;
          last_synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          type: string;
          is_connected?: boolean;
          config?: Record<string, unknown>;
        };
        Update: Partial<Database["public"]["Tables"]["integrations"]["Insert"]>;
      };
      org_members: {
        Row: {
          id: string;
          org_id: string;
          user_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          user_id: string;
          role?: string;
        };
        Update: Partial<Database["public"]["Tables"]["org_members"]["Insert"]>;
      };
      campaign_prospects: {
        Row: {
          id: string;
          campaign_id: string;
          prospect_id: string;
          current_step: number;
          status: string;
          next_send_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          prospect_id: string;
          current_step?: number;
          status?: string;
          next_send_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["campaign_prospects"]["Insert"]>;
      };
    };
    Views: {
      campaign_analytics: {
        Row: {
          campaign_id: string;
          campaign_name: string;
          org_id: string;
          total_prospects: number;
          emails_sent: number;
          emails_delivered: number;
          emails_opened: number;
          emails_clicked: number;
          emails_bounced: number;
          replies_total: number;
          replies_interested: number;
          meetings_booked: number;
          meetings_completed: number;
        };
      };
    };
    Functions: {
      get_user_org_ids: {
        Args: Record<string, never>;
        Returns: string[];
      };
      get_daily_metrics: {
        Args: {
          p_org_id: string;
          p_start_date?: string;
          p_end_date?: string;
        };
        Returns: {
          metric_date: string;
          emails_sent: number;
          emails_opened: number;
          replies: number;
          meetings: number;
        }[];
      };
    };
  };
}
